# Python image to use.
FROM python:3.10

# Set the working directory to /app
WORKDIR /app/backend

# copy the requirements file used for dependencies
COPY . /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the working directory contents into the container at /app
COPY . .

# Run app.py when the container launches
ENTRYPOINT ["python", "local_backend_app.py"]