name: Aggregate hourly downloads triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
      - ".github/workflows/lint-test-function.yml"

concurrency:
  # cancel any existing unfinished jobs if this workflow is retriggered
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint-test:
    name: Lint test hourly downloads
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: aggregate_hourly_downloads

  call-deploy:
    needs: call-lint-test
    # if: github.ref == 'refs/heads/main'
    name: Deploy hourly downloads
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: aggregate_hourly_downloads
