name: Monthly submissions triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/monthly_submissions/**"
      - "terraform/monthly_submissions/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/monthly_submissions/**"
      - "terraform/monthly_submissions/**"
      - ".github/workflows/lint-test-function.yml"

concurrency:
  # cancel any existing unfinished jobs if this workflow is retriggered
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint-test:
    name: Lint test monthly submissions
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: monthly_submissions

  call-deploy:
    needs: call-lint-test
    if: github.ref == 'refs/heads/main'
    name: Deploy monthly submissions
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: monthly_submissions
